"""
Auto-transpiled from PineScript: Saty Phase Strategy
Generated by Wale Pine Engine — event-driven TradingView semantics.
"""

import math

import numpy as np
import pandas as pd

from src import pine_ta as ta
from src.strategies.pine_base import PineStrategy, NA, na, nz, _sv, _truthy, _pine_range


def _sign(x):
    return (x > 0) - (x < 0)


def _avg(*xs):
    return sum(xs) / len(xs)


class SatyPhaseStrategyStrategy(PineStrategy):
    """Saty Phase Strategy (auto-transpiled)"""

    INITIAL_CAPITAL = 100000.0
    QTY_TYPE = 'fixed'
    QTY_VALUE = 1.0
    COMMISSION_PCT = 0.0
    PYRAMIDING = 1
    VAR_DEFAULTS = {'compression_tracker': False, 'tbl': float('nan'), 'lastPricePivotHigh': float('nan'), 'lastOscPivotHigh': float('nan')}

    def __init__(self, **params):
        super().__init__(**params)
        self.params.setdefault('show_label', True)
        self.params.setdefault('show_zone_crosses', True)
        self.params.setdefault('show_extreme_crosses', True)

    def precompute(self, df, p):
        n = len(df)
        close = df['close'].to_numpy(dtype=float)
        open_ = df['open'].to_numpy(dtype=float) if 'open' in df.columns else close
        high = df['high'].to_numpy(dtype=float) if 'high' in df.columns else close
        low = df['low'].to_numpy(dtype=float) if 'low' in df.columns else close
        volume = df['volume'].to_numpy(dtype=float) if 'volume' in df.columns else np.zeros(n)

        pivot = ta.ema(close, 21.0)
        above_pivot = (close >= pivot)
        bband_offset = (2.0 * ta.stdev(close, 21.0))
        bband_up = (pivot + bband_offset)
        bband_down = (pivot - bband_offset)
        compression_threshold_up = (pivot + (2.0 * ta.atr(high, low, close, 14.0)))
        compression_threshold_down = (pivot - (2.0 * ta.atr(high, low, close, 14.0)))
        expansion_threshold_up = (pivot + (1.854 * ta.atr(high, low, close, 14.0)))
        expansion_threshold_down = (pivot - (1.854 * ta.atr(high, low, close, 14.0)))
        compression = np.where(above_pivot, (bband_up - compression_threshold_up), (compression_threshold_down - bband_down))
        in_expansion_zone = np.where(above_pivot, (bband_up - expansion_threshold_up), (expansion_threshold_down - bband_down))
        expansion = (ta.shift(compression, 1.0) <= ta.shift(compression, 0.0))
        raw_signal = (((close - pivot) / (3.0 * ta.atr(high, low, close, 14.0))) * 100.0)
        oscillator = ta.ema(raw_signal, 3.0)
        leaving_accumulation = (np.asarray((ta.shift(oscillator, 1.0) <= (-61.8)), dtype=bool) & np.asarray((oscillator > (-61.8)), dtype=bool))
        leaving_extreme_down = (np.asarray((ta.shift(oscillator, 1.0) <= (-100.0)), dtype=bool) & np.asarray((oscillator > (-100.0)), dtype=bool))
        leaving_extreme_up = (np.asarray((ta.shift(oscillator, 1.0) >= 100.0), dtype=bool) & np.asarray((oscillator < 100.0), dtype=bool))
        buySignal = (np.asarray(leaving_accumulation, dtype=bool) | np.asarray(leaving_extreme_down, dtype=bool))
        overboughtNow = (np.asarray((ta.shift(oscillator, 1.0) >= 100.0), dtype=bool) & np.asarray((oscillator < 100.0), dtype=bool))
        pivotLen = 3.0
        pricePH = ta.pivothigh(high, pivotLen, pivotLen)
        oscPH = ta.pivothigh(oscillator, pivotLen, pivotLen)
        newPricePivot = ~np.asarray(np.isnan(np.asarray(pricePH, dtype=float)), dtype=bool)
        newOscPivot = ~np.asarray(np.isnan(np.asarray(oscPH, dtype=float)), dtype=bool)

        return {'above_pivot': above_pivot, 'bband_down': bband_down, 'bband_offset': bband_offset, 'bband_up': bband_up, 'buySignal': buySignal, 'close': close, 'compression': compression, 'compression_threshold_down': compression_threshold_down, 'compression_threshold_up': compression_threshold_up, 'expansion': expansion, 'expansion_threshold_down': expansion_threshold_down, 'expansion_threshold_up': expansion_threshold_up, 'high': high, 'in_expansion_zone': in_expansion_zone, 'leaving_accumulation': leaving_accumulation, 'leaving_extreme_down': leaving_extreme_down, 'leaving_extreme_up': leaving_extreme_up, 'low': low, 'newOscPivot': newOscPivot, 'newPricePivot': newPricePivot, 'open': open_, 'oscPH': oscPH, 'oscillator': oscillator, 'overboughtNow': overboughtNow, 'pivot': pivot, 'pivotLen': pivotLen, 'pricePH': pricePH, 'raw_signal': raw_signal}

    def on_bar(self, i, s, b, p):
        green = NA
        red = NA
        magenta = NA
        light_gray = NA
        gray = NA
        dark_gray = NA
        yellow = NA
        if _truthy((s.expansion[i] and (s.in_expansion_zone[i] > 0.0))):
            self.v['compression_tracker'] = False
        elif _truthy((s.compression[i] <= 0.0)):
            self.v['compression_tracker'] = True
        else:
            self.v['compression_tracker'] = False
        if _truthy(((i == len(s.close) - 1) and p['show_label'])):
            pass
        if _truthy(((self.v['compression_tracker'] == False) and p['show_label'])):
            pass
        if _truthy(s.newPricePivot[i]):
            self.v['lastPricePivotHigh'] = s.pricePH[i]
        if _truthy(s.newOscPivot[i]):
            self.v['lastOscPivotHigh'] = s.oscPH[i]
        divergenceBearish = False
        if _truthy((((s.newPricePivot[i] and s.newOscPivot[i]) and (not na(self.var_prev('lastPricePivotHigh', i, int(1.0))))) and (not na(self.var_prev('lastOscPivotHigh', i, int(1.0)))))):
            divergenceBearish = ((s.pricePH[i] > self.var_prev('lastPricePivotHigh', i, int(1.0))) and (s.oscPH[i] < self.var_prev('lastOscPivotHigh', i, int(1.0))))
        exitSignal = (s.overboughtNow[i] or divergenceBearish)
        if _truthy(s.buySignal[i]):
            b.entry('Long', 1)
        if _truthy((b.position_size > 0.0)):
            if _truthy(exitSignal):
                b.close('Long', comment='Peak Overbought or Bearish Div')

    def param_grid(self):
        return PARAM_GRID_DEFAULT


PARAM_GRID_DEFAULT = {
    'show_label': [0.9, 1.0, 1.1],
    'show_zone_crosses': [0.9, 1.0, 1.1],
    'show_extreme_crosses': [0.9, 1.0, 1.1],
}
