"""
Auto-transpiled from PineScript: Saty Phase - High WR
Generated by Wale Pine Engine — event-driven TradingView semantics.
"""

import math

import numpy as np
import pandas as pd

from src import pine_ta as ta
from src.strategies.pine_base import PineStrategy, NA, na, nz, _sv, _truthy


def _sign(x):
    return (x > 0) - (x < 0)


class SatyPhaseHighWrStrategy(PineStrategy):
    """Saty Phase - High WR (auto-transpiled)"""

    INITIAL_CAPITAL = 100000.0
    QTY_TYPE = 'percent_of_equity'
    QTY_VALUE = 100.0
    COMMISSION_PCT = 0.0
    PYRAMIDING = 1
    VAR_DEFAULTS = {'entryPrice': float('nan'), 'highestSinceEntry': float('nan'), 'trailingActive': False, 'trailStopPrice': float('nan')}

    def __init__(self, **params):
        super().__init__(**params)
        self.params.setdefault('stop_loss_pct', 14.0)
        self.params.setdefault('trailing_pct', 0.4)
        self.params.setdefault('profit_target_pct', 4.5)
        self.params.setdefault('use_ob_exit', False)
        self.params.setdefault('entry_threshold', -50.0)

    def precompute(self, df, p):
        n = len(df)
        close = df['close'].to_numpy(dtype=float)
        open_ = df['open'].to_numpy(dtype=float) if 'open' in df.columns else close
        high = df['high'].to_numpy(dtype=float) if 'high' in df.columns else close
        low = df['low'].to_numpy(dtype=float) if 'low' in df.columns else close
        volume = df['volume'].to_numpy(dtype=float) if 'volume' in df.columns else np.zeros(n)

        pivot = ta.ema(close, 21.0)
        atr14 = ta.atr(high, low, close, 14.0)
        raw_signal = (((close - pivot) / (3.0 * atr14)) * 100.0)
        oscillator = ta.ema(raw_signal, 3.0)
        leaving_entry = (np.asarray((ta.shift(oscillator, 1.0) <= p['entry_threshold']), dtype=bool) & np.asarray((oscillator > p['entry_threshold']), dtype=bool))
        leaving_extreme = (np.asarray((ta.shift(oscillator, 1.0) <= (-100.0)), dtype=bool) & np.asarray((oscillator > (-100.0)), dtype=bool))

        return {'atr14': atr14, 'close': close, 'high': high, 'leaving_entry': leaving_entry, 'leaving_extreme': leaving_extreme, 'low': low, 'open': open_, 'oscillator': oscillator, 'pivot': pivot, 'raw_signal': raw_signal}

    def on_bar(self, i, s, b, p):
        if _truthy(((s.leaving_entry[i] or s.leaving_extreme[i]) and (b.position_size == 0.0))):
            b.entry('Long', 1)
            self.v['entryPrice'] = s.close[i]
            self.v['highestSinceEntry'] = s.close[i]
            self.v['trailingActive'] = False
            self.v['trailStopPrice'] = NA
        if _truthy((b.position_size > 0.0)):
            self.v['highestSinceEntry'] = max(self.v['highestSinceEntry'], s.high[i])
            currentPnL = (((s.close[i] - self.v['entryPrice']) / self.v['entryPrice']) * 100.0)
            stopLossPrice = (self.v['entryPrice'] * (1.0 - (p['stop_loss_pct'] / 100.0)))
            if _truthy(((currentPnL >= p['profit_target_pct']) and (not self.v['trailingActive']))):
                self.v['trailingActive'] = True
                self.v['trailStopPrice'] = (self.v['highestSinceEntry'] * (1.0 - (p['trailing_pct'] / 100.0)))
            if _truthy(self.v['trailingActive']):
                self.v['trailStopPrice'] = max(self.v['trailStopPrice'], (self.v['highestSinceEntry'] * (1.0 - (p['trailing_pct'] / 100.0))))
            if _truthy((s.low[i] <= stopLossPrice)):
                b.close('Long', comment='SL')
                self.v['entryPrice'] = NA
                self.v['highestSinceEntry'] = NA
                self.v['trailingActive'] = False
                self.v['trailStopPrice'] = NA
            elif _truthy((self.v['trailingActive'] and (s.low[i] <= self.v['trailStopPrice']))):
                b.close('Long', comment='Trail')
                self.v['entryPrice'] = NA
                self.v['highestSinceEntry'] = NA
                self.v['trailingActive'] = False
                self.v['trailStopPrice'] = NA
        if _truthy(((b.position_size == 0.0) and (b.position_size_at(int(1.0)) > 0.0))):
            self.v['entryPrice'] = NA
            self.v['highestSinceEntry'] = NA
            self.v['trailingActive'] = False
            self.v['trailStopPrice'] = NA

    def param_grid(self):
        return PARAM_GRID_DEFAULT


<<<<<<< HEAD
=======
    def _calc_rsi(self, series, period=14):
        delta = series.diff()
        gain = delta.where(delta > 0, 0.0)
        loss = -delta.where(delta < 0, 0.0)
        avg_gain = gain.ewm(alpha=1/period, adjust=False).mean()
        avg_loss = loss.ewm(alpha=1/period, adjust=False).mean()
        rs = avg_gain / avg_loss
        return 100 - (100 / (1 + rs))

    def _calc_macd(self, series, fast=12, slow=26, signal=9):
        ema_fast = series.ewm(span=fast, adjust=False).mean()
        ema_slow = series.ewm(span=slow, adjust=False).mean()
        macd = ema_fast - ema_slow
        signal_line = macd.ewm(span=signal, adjust=False).mean()
        hist = macd - signal_line
        return macd, signal_line, hist

# Auto-generated parameter grid
>>>>>>> origin/main
PARAM_GRID_DEFAULT = {
    'stop_loss_pct': [12.6, 14.0, 15.4],
    'trailing_pct': [0.36, 0.4, 0.44],
    'profit_target_pct': [4.05, 4.5, 4.95],
    'use_ob_exit': [False],
    'entry_threshold': [-45.0, -50.0, -55.0],
}
