"""
Auto-transpiled from PineScript: Smart Trend Momentum Strategy v6
Generated by Wale Pine Engine — event-driven TradingView semantics.
"""

import math

import numpy as np
import pandas as pd

from src import pine_ta as ta
from src.strategies.pine_base import PineStrategy, NA, na, nz, _sv, _truthy


def _sign(x):
    return (x > 0) - (x < 0)


class SmartTrendMomentumStrategyV6Strategy(PineStrategy):
    """Smart Trend Momentum Strategy v6 (auto-transpiled)"""

    INITIAL_CAPITAL = 10000.0
    QTY_TYPE = 'percent_of_equity'
    QTY_VALUE = 5.0
    COMMISSION_PCT = 0.05
    PYRAMIDING = 1
    VAR_DEFAULTS = {}

    def __init__(self, **params):
        super().__init__(**params)
        self.params.setdefault('emaFastLen', 20)
        self.params.setdefault('emaSlowLen', 50)
        self.params.setdefault('rsiLen', 14)
        self.params.setdefault('rsiMin', 45)
        self.params.setdefault('rsiMax', 70)
        self.params.setdefault('atrLen', 14)
        self.params.setdefault('slMult', 1.8)
        self.params.setdefault('tpMult', 2.8)
        self.params.setdefault('useShorts', False)

    def precompute(self, df, p):
        n = len(df)
        close = df['close'].to_numpy(dtype=float)
        open_ = df['open'].to_numpy(dtype=float) if 'open' in df.columns else close
        high = df['high'].to_numpy(dtype=float) if 'high' in df.columns else close
        low = df['low'].to_numpy(dtype=float) if 'low' in df.columns else close
        volume = df['volume'].to_numpy(dtype=float) if 'volume' in df.columns else np.zeros(n)

        emaFast = ta.ema(close, p['emaFastLen'])
        emaSlow = ta.ema(close, p['emaSlowLen'])
        rsiVal = ta.rsi(close, p['rsiLen'])
        atrVal = ta.atr(high, low, close, p['atrLen'])
        upTrend = (emaFast > emaSlow)
        downTrend = (emaFast < emaSlow)

        return {'atrVal': atrVal, 'close': close, 'downTrend': downTrend, 'emaFast': emaFast, 'emaSlow': emaSlow, 'high': high, 'low': low, 'open': open_, 'rsiVal': rsiVal, 'upTrend': upTrend}

    def on_bar(self, i, s, b, p):
        longCond = (((s.upTrend[i] and (s.rsiVal[i] > p['rsiMin'])) and (s.rsiVal[i] < p['rsiMax'])) and (b.position_size == 0.0))
        shortCond = (((p['useShorts'] and s.downTrend[i]) and (s.rsiVal[i] < (100.0 - p['rsiMin']))) and (b.position_size == 0.0))
        if _truthy(longCond):
            b.entry('Long', 1)
        if _truthy(shortCond):
            b.entry('Short', -1)
        if _truthy((b.position_size > 0.0)):
            longStop = (b.position_avg_price - (s.atrVal[i] * p['slMult']))
            longTake = (b.position_avg_price + (s.atrVal[i] * p['tpMult']))
            b.exit('Long Exit', from_entry='Long', stop=longStop, limit=longTake)
        if _truthy((b.position_size < 0.0)):
            shortStop = (b.position_avg_price + (s.atrVal[i] * p['slMult']))
            shortTake = (b.position_avg_price - (s.atrVal[i] * p['tpMult']))
            b.exit('Short Exit', from_entry='Short', stop=shortStop, limit=shortTake)

    def param_grid(self):
        return PARAM_GRID_DEFAULT


PARAM_GRID_DEFAULT = {
    'emaFastLen': [15, 20, 25],
    'emaSlowLen': [45, 50, 55],
    'rsiLen': [9, 14, 19],
    'rsiMin': [40, 45, 50],
    'rsiMax': [70],
    'atrLen': [14],
    'slMult': [1.8],
    'tpMult': [2.8],
    'useShorts': [False],
}
